### ISSUE TITLE
Droplet

### ISSUE THREAD

**Issue by NathanielBrassell** [Softdev-project/Assassin#1]
I received an email today from Digital Ocean saying that my droplet was compromised and was attacking other droplets. They have suspended my account until it is fixed.

**Comment by SingleDreamer** [comment]
…. well.

On Tue, Dec 23, 2014 at 7:37 PM, Nathaniel Brassell <
notifications@github.com> wrote:

> I received an email today from Digital Ocean saying that my droplet was
> compromised and was attacking other droplets. They have suspended my
> account until it is fixed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Softdev-project/Assassin/issues/1.

## 

Student of Stuyvesant High School
718-737-3102
jessica.hl.ng5@gmail.com
