### ISSUE TITLE
Testing Website on mobile browsers

### ISSUE THREAD

**Issue by jasonluX13** [Softdev-project/Assassin#2]
Has anyone tried testing the website on their phones? I just tried it and the map does not load.

**Comment by SingleDreamer** [comment]
give me a minute to test, but does your mobile give your browser permission
to use its location?

On Mon, Jan 19, 2015 at 3:20 PM, jasonluX13 notifications@github.com
wrote:

> Has anyone tried testing the website on their phones? I just tried it and
> the map does not load.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Softdev-project/Assassin/issues/2.

## 

Student of Stuyvesant High School
718-737-3102
jessica.hl.ng5@gmail.com

**Comment by SingleDreamer** [comment]
yeah check the location services mine worked once i changed the permissions

On Mon, Jan 19, 2015 at 8:01 PM, Jessica Ng jessica.hl.ng5@gmail.com
wrote:

> give me a minute to test, but does your mobile give your browser
> permission to use its location?
> 
> On Mon, Jan 19, 2015 at 3:20 PM, jasonluX13 notifications@github.com
> wrote:
> 
> > Has anyone tried testing the website on their phones? I just tried it and
> > the map does not load.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Softdev-project/Assassin/issues/2.
> 
> ## 
> 
> Student of Stuyvesant High School
> 718-737-3102
> jessica.hl.ng5@gmail.com

## 

Student of Stuyvesant High School
718-737-3102
jessica.hl.ng5@gmail.com
